//! 将 `payload/` 目录整树内嵌进安装器可执行文件。
//!
//! 由发布流程（或 installer/prepare-payload.ps1）预先把分发包内容
//! 填入 payload/，本脚本递归扫描后生成 `PAYLOAD` 静态表（include_bytes!），
//! 因此最终产物是**单文件安装器**，双击即可安装，无需随附任何目录。
//!
//! 防御性排除：`data/`、`logs/`、`*.log`（用户数据/日志绝不入包）。

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=payload");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(v) => PathBuf::from(v),
        Err(e) => {
            emit_compile_error(&format!("CARGO_MANIFEST_DIR unavailable: {e}"));
            return;
        }
    };
    let payload_dir = manifest_dir.join("payload");
    if !payload_dir.is_dir() {
        emit_compile_error(&format!(
            "payload/ 目录不存在：{}。请先运行 installer/prepare-payload.ps1 填充分发包内容。",
            payload_dir.display()
        ));
        return;
    }

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if let Err(e) = walk(&payload_dir, &payload_dir, &mut files) {
        emit_compile_error(&format!("扫描 payload/ 失败: {e}"));
        return;
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));

    if files.is_empty() {
        emit_compile_error(
            "payload/ 目录为空。请先运行 installer/prepare-payload.ps1 填充分发包内容。",
        );
        return;
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub static PAYLOAD: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &files {
        let abs_str = abs.to_string_lossy().replace('\\', "/");
        out.push_str(&format!("    (\"{rel}\", include_bytes!(\"{abs_str}\")),\n"));
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap_or_default()).join("payload.rs");
    if let Err(e) = fs::write(&out_path, out) {
        // 写失败时 include!(payload.rs) 会在主编译期报错，无需在此 panic。
        println!("cargo:warning=evorule-setup build.rs: 写 payload.rs 失败: {e}");
    }
}

fn walk(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    let entries = fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("{}: {e}", dir.display()))?;
        let path = entry.path();
        let name = entry
            .file_name()
            .to_string_lossy()
            .trim()
            .to_string();
        if path.is_dir() {
            // 防御性排除：用户数据与日志不入包
            if name.eq_ignore_ascii_case("data") || name.eq_ignore_ascii_case("logs") {
                continue;
            }
            walk(root, &path, files)?;
        } else {
            if name.to_ascii_lowercase().ends_with(".log") {
                continue;
            }
            let rel = path
                .strip_prefix(root)
                .map_err(|e| format!("strip_prefix {}: {e}", path.display()))?
                .to_string_lossy()
                .replace('\\', "/");
            files.push((rel, path));
        }
    }
    Ok(())
}

fn emit_compile_error(msg: &str) {
    let out = format!(
        "// @generated by build.rs — do not edit\ncompile_error!(\"{msg}\");\n"
    );
    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap_or_default()).join("payload.rs");
    if let Err(e) = fs::write(&out_path, out) {
        println!("cargo:warning=evorule-setup build.rs: 写 payload.rs 失败: {e}");
    }
}
